name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install production dependencies
        run: |
          mkdir temp-prod
          cp package*.json temp-prod/
          cd temp-prod && npm ci --omit=dev
          
      - name: Prepare deployment package
        run: |
          mkdir deploy-package
          cp -r dist deploy-package/
          cp package*.json deploy-package/
          cp -r shared deploy-package/
          cp drizzle.config.ts deploy-package/ 2>/dev/null || true
          cp -r temp-prod/node_modules deploy-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AnnualVacationCanvasing-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
